### ISSUE TITLE
Home view

### ISSUE THREAD

**Issue by JScriber** [JScriber/Kaboom#10]

**Comment by JScriber** [comment]
Wireframe : 
![home_page](https://user-images.githubusercontent.com/27382087/49617006-1c0ee300-f9b3-11e8-8b4e-f4ee378f9e6e.png)

**Comment by Alexis-Pannetier** [comment]
![home_page](https://user-images.githubusercontent.com/35290061/50904923-d3b76a80-1421-11e9-9d19-55f3f91f8f65.png)

Une fois l'utilisateur identifié un bouton "disconnect" remplacera le bouton "sign-in" et "log-in" peut on utiliser ce même espace pour ajouter un bouton "profil" ?
